### ISSUE TITLE
support jpg images

### ISSUE THREAD

**Issue by nkh** [stefanhaustein/TerminalImageViewer#8]
103 ~  xpix Downloads/gd.jpg
Exception in thread "main" javax.imageio.IIOException: Can't read input file!
        at javax.imageio.ImageIO.read(ImageIO.java:1301)
        at TerminalImageViewer.loadImage(TerminalImageViewer.java:139)
        at TerminalImageViewer.convert(TerminalImageViewer.java:116)
        at TerminalImageViewer.main(TerminalImageViewer.java:73)

**Comment by stefanhaustein** [comment]
Jpeg images should work... Do you have a url for the jpeg that doesn't?

**Comment by nkh** [comment]
local file, no jpeg opens, maybe some dependency?

**Comment by stefanhaustein** [comment]
Can you add an example file to the bug? ImageIO should handle jpegs properly by default.

**Comment by nkh** [comment]
![1236856_10151848589554019_1808449366_n](https://cloud.githubusercontent.com/assets/45409/18933386/cb7a5072-85d4-11e6-8915-10aabf3d4b14.jpg)

**Comment by stefanhaustein** [comment]
Works for me without problems. Which Java version are you using? Which OS?

**Comment by stefanhaustein** [comment]
Can't reproduce. Please update your JRE if feasible and re-open with more information if the problem persist.
